# permissions for end users to view certmanageraddons.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: certmanageraddon-viewer-role
rules:
- apiGroups:
  - addons.x-k8s.io
  resources:
  - certmanageraddons
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - addons.x-k8s.io
  resources:
  - certmanageraddons/status
  verbs:
  - get
