# permissions for end users to edit certmanageraddons.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: certmanageraddon-editor-role
rules:
- apiGroups:
  - addons.x-k8s.io
  resources:
  - certmanageraddons
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - addons.x-k8s.io
  resources:
  - certmanageraddons/status
  verbs:
  - get
